// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krepbhajbehoflpcxdvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZXBiaGFqYmVob2ZscGN4ZHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTAwMzgsImV4cCI6MjA1NTQ4NjAzOH0.F9g6pNi8PSv8lD_ktLazV5SnaLF_zSSiakgp9lqZmYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);